# Antecedentes de la aplicación de un sistema de costos en universidades

Previo al análisis, ejecución y revisión del modelo de costos propuesto para la Universidad Nacional de Colombia, se realizó una revisión teórica de la aplicación de sistemas de costos en diferentes universidades que sirviera de base para los miembros del equipo de trabajo durante la aplicación del modelo al caso particular de la universidad; por lo que se hace una breve descripción de las ideas más representativas de los casos indagados.

## España

La implementación de un sistema de control de costos que le permitiera mantener informado a los responsables de sus objetivos planteados, e incluso disponer de información externa que revelara a los grupos interesados la productividad de los recursos asignados, en el que prime la noción de racionalización en la asignación de los recursos por parte de las autoridades públicas.

Esto fue el resultado de un nuevo panorama universitario europeo descrito por dos situaciones esenciales, la primera, la necesidad de un cálculo y análisis de los costos diferenciados para cada servicio en la universidad pública, en este caso, la docencia y la investigación considerados como los dos pilares universitarios de interés público; y la segunda, cambios en la Universidad Pública Española, que van desde la autonomía universitaria consagrada a partir de la ley de reforma de 1983, pasando por la descentralización del modelo de educación superior -- Ley Orgánica 9/1992 de 23 de diciembre, hasta la adecuación al modelo del espacio europeo de educación superior, recomendación de la ley orgánica 6/2001 de Universidad LOU, modificada por la ley orgánica 4/2007 de 12 de Abril LOMLOU, y cuyo proceso de construcción se inició con la declaración de la Sorbona 1998 y se confirmó y amplió con la declaración de Bolonia 1999 y el comunicado de Praga 2001. (López Esteban, pág. 5)

Se habla también de la intención de implementar la contabilidad analítica en las universidades españolas, que hasta su momento no se había podido llevar a cabo debido a la falta de voluntad política. Sin embargo, la situación económica del país llevo a que mediante el real decreto -- Ley 14 2012 de 20 de abril se materializará la necesidad de controlar los gastos de las administraciones públicas, por medio de la instauración urgente de racionalización del gasto público en el ámbito educativo. Lo que llama la atención de este real decreto es la mención explícita que se hace respecto al porcentaje que el alumno debe cubrir de los costos con el pago de sus matrículas; teniendo entonces la Universidad Pública Española la obligación de responder a la pregunta de ¿y valor tiene un título de grado?. Así mismo, se considera a la investigación como una línea de interés que debe ser objeto de estudio en el modelo de costos español, por cuanto es una de las actividades primordiales que desarrollan las Universidades y hospitales, quienes son las responsables en principio de proveer bienes públicos puros. (López Esteban, 2013, pág. 6).

Los primeros intentos de instaurar un modelo de contabilidad analítica en las universidades españolas datan de 1983 con la publicación del grupo 9 del Plan general de Contabilidad Pública. Con ella, la iniciativa más importante que se ejecutó fue el Sistema de Contabilidad Analítica para las Universidades SCAU, realizado en 1991 por la IGAE, a petición de las propias instituciones quienes estaban interesadas en conocer sus costos y gestionar eficientemente los recursos que financian el sistema. No obstante, la IGAE expidió en 1994 el proyecto Contabilidad Analítica Normalizada de Organismos Autónomos CANOA con el objetivo de emitir lenguaje y terminología común y generalizar unas pautas de cálculo homogéneo y comparable de costos; y en este sentido la implementación y ejecución del modelo se materializó por varias universidades, dentro de las que se destacan: a) Universidad de Oviedo 2000; b) Universidad Jaime I 2000; c) Universidad de Zaragoza 2001; d) Universidades Andaluzas 2007; e) Universidad de Alcala de Henares y UNED 2007; f) Universidad Carlos III de Madrid; g) Universidad Pompeu Fabra 2008 & Universidad de las Palmas de Gran Canaria 2002 -- 2006.

Sin embargo, es importante recordar en este punto que el modelo propuesto fue de carácter estándar y fue concebido para instituciones con objetivos y estructuras organizativas similares, por lo que al aplicarlo en las universidades presentó inicialmente cierto carácter ambiguo o falta de precisión en algunos puntos particulares; por lo que fue necesario adaptar y personalizar el modelo al funcionamiento general de la universidad en cuestión (López Esteban, 2013, págs. 19 - 20)

## Argentina

Partiendo de la idea de que la contabilidad de gestión estratégica podría constituirse en una herramienta importante en el análisis de la cadena de valor que incluye una revisión estratégica de los costos, en donde el principal objetivo es mejorar la eficiencia en el uso de los recursos; las Universidades Nacionales Argentinas comenzaron a desarrollar procesos de planificación estratégica institucional. Por lo que para efectos de sustentación de este documento, se revisó el texto (El costeo basado en la actividad en las universidades: Una herramienta para la gestión estrategica y la creación de valor, pág. 4) de Cecilia Rita Ficco; en él, se referencian algunas experiencias puntuales de aplicación de modelos de contabilidad de gestión en universidades que sirvieron para que, particularmente la Universidad Nacional de Rio Cuarto UNRC, iniciara una serie de proyectos de investigación en su facultad de ciencias económicas para configurar un modelo de costos para la gestión universitaria basado en las ideas fundamentales del ABC.

En general se justifica el uso del modelo ABC por cuanto evita repartir costos entre los productos usando como único criterio de asignación el volumen de producción y otros asociados a él, tal y como lo hace el costeo tradicional. No obstante, el modelo ejecutado por la mayoría de las instituciones fue desarrollado por medio de los siguientes pasos: "(i) Determinar la estructura de las actividades existentes en la organización; (ii) Asignar los costos a las actividades que los han consumido; y, (iii) Calcular el costo de cada producto u objeto de costo, a través de su vinculación con el costo de las actividades" (Ficco, 2011, pág. 7)

## Chile

Se revisó el caso particular de la Universidad de Chile, en donde se implementó la metodología de costo ABC + tradicional por medio de la siguientes tres etapas: (i) Definición de tareas o acciones en actividades; (ii) Determinación del costo de las actividades; (iii) Cálculo del costo de los Outputs. Para este caso, los principales procesos o actividades que se identificaron fueron: la docencia, investigación, innovación, extensión y administración académica. La propuesta es una aproximación de lo que podría ser un modelo para Universidades públicas con financiamiento privado, que, para este ejemplo, la universidad es considerada estatal de acuerdo a su presupuesto del 2016, pero que solventa sus gastos con un aporte del 6% del estado. La elección del costeo ABC se dio como resultado de: a) realizar una asignación de costos de las actividades que se están ejecutando y que generan valor en la institución a través del uso eficiente de los recursos; b) Dar una mejor comprensión de los resultados de gestión por cada departamento, c) favorecer la gestión administración, entendiendo la asignación de costos y otorgando información útil que sirva para la toma de decisiones de los distintos departamentos dentro de la institución; d) Optimizar la mayor parte de los procesos o actividades considerando que las universidades públicas Chilenas reciben un aporte por parte del estado prácticamente nulo (Balmaceda Lira & Guerra Vera, 2017).

## Colombia: Universidad de Antioquia y EAFIT

En Colombia se han implementado sistemas de costo en algunas universidades con resultados exitosos reconociendo su beneficio y valor agregado como instrumento de gestión y control como se pudo comprobar en el estudio realizado por Giraldo, Henao & Restrepo (2014) afirmando que:

> Al comparar la utilización de la información que puede proporcionar el modelo de costos en las dos universidades analizadas, se puede detectar que tanto la Universidad de Antioquia como EAFIT utilizan los costos para controlar y racionalizar recursos, sin embargo en la Universidad EAFIT la información de costos llega a todas las dependencias y se utiliza mucho esta información en las áreas de asesoría y consultoría para efectos de licitaciones y en el resto de dependencias para retroalimentarse y optimizar los recursos con el objetivo de mejorar la rentabilidad, mientras que en la Universidad de Antioquia la información suministrada por el modelo de costos ABC básicamente se utiliza para el control en la ejecución del presupuesto, su usuario principal es la Vicerrectoría Administrativa, pocas dependencias hacen uso de la información: regionalización, investigación y extensión que son las que más utilizan los costos ya que constantemente están iniciando nuevos proyectos para controlar los recursos, en esta universidad poco se utiliza la información de costos para la toma de decisiones.

> Es importante destacar cómo la implementación de un modelo de costos en dos instituciones que tuvieron la misma asesoría en su montaje, tiene desarrollos y beneficios muy diferentes, lo que permite concluir que el éxito de un modelo de costos no depende tanto del consultor o empresa encargada de la implementación, sino de la cultura de costos que se pueda crear al interior de la organización.

> De acuerdo a todo lo anterior se acepta la segunda respuesta tentativa (hipótesis) del modelo donde se planteó que el beneficio de un modelo de costos ABC se encuentra ligado al compromiso que tiene cada institución por mantener y cada día mejorar el modelo, por difundir la información que arroja este a través de sus diferentes periodos a toda la organización y del compromiso o cultura de costos que tenga la institución para que la corrida del modelo se realice en el tiempo oportuno para una buena toma de decisiones. (Giraldo, Henao, & Restrepo, 2014, pág. 16)
