# Marco conceptual del sistema de costos en la Universidad

## ¿Qué es un sistema de costos?

Un sistema de costos hace referencia a "El Conjunto de procedimientos, técnicas, registros e informes estructurados sobre la base de la teoría de la partida doble y otros principios técnicos, que tiene por objeto la determinación de los costos unitarios y el control de las operaciones efectuadas" (Ortega Pérez de León, 1998, Citado en García Colín, 1996, pág. 84)[@GarciaColin pp. 84].

## ¿Cuál es el propósito?

El sistema de costos gana relevancia en el proceso de toma de decisiones; por lo que se espera, que una vez aplicada la metodología propuesta en la Universidad Nacional de Colombia, sea útil para analizar y evaluar situaciones relacionadas con el objetivo general propuesto en ella: determinar el costo por estudiante para cada uno de los programas de pregrado y posgrado; y determinar el costo de cada proyecto de investigación y extensión.

Si bien es cierto que el modelo propuesto se realiza con base en fuentes de información históricas, se prevé que su aplicación sea útil en la generación de datos e informes que permitan a los usuarios de la información generar mejores procesos de planeación y control, al tiempo que se pueda generar un sistema capaz de responder a las necesidades y/o intereses informacionales que los estados financieros por sí solos no pueden proporcionar.

Se pretende que el modelo permita vislumbrar la gestión que se hace con los recursos al interior de la universidad; se busca implementar, analizar, ajustar y revisar un modelo de costos que sirva posteriormente a las diferentes estructuras organizativas para que su gestión pueda optimizarse, y que los interesados en la información financiera (Stakeholders) posean una fuente de información adicional a los estados financieros, para que sus decisiones sean tomadas con base en criterios de racionalidad, economía y eficiencia.

## Características de un sistema de costos

Revisando a María Teresa Ortega, se observa que previo a la definición de un modelo de costos es importante partir del conocimiento del conjunto de actividades que se desarrollan en la Universidad, y los recursos consumidos para su ejecución. Adicionalmente, se deben establecer las etapas de definición del modelo, identificando las relaciones entre las diferentes unidades en una primera etapa, para así determinar los costos que se deben ceder o trasladar entre dichas unidades (Ortega, Rodríguez Ariza, & López Pérez, 2007)[@OrtegaRodriguez].

El sistema de costos definido para la Universidad, parte del análisis de la estructura organizativa de la Universidad y la definición de las unidades (sedes, facultades, departamentos, unidades especiales como Unimedios, Unisalud, Editorial, Fondo Pensional y Regalías) que se tendrán en cuenta para el costeo. Posteriormente, se realiza la identificación de las interacciones entre las diferentes unidades con el fin de realizar los respectivos traslados de costos.

El modelo de costos implementado por la universidad considera los componentes básicos del modelo de Costos ABC, el cual es aplicable anualmente posterior al cierre contable y a la consolidación de la información de los Programas de Trabajo Académico - PTA.

## Beneficios de la implementación del sistema de costos

La información que produce un sistema de contabilidad de costos, refiriéndose a todo tipo de empresas incluyendo las pymes, ayuda a los administradores en la planeación, el control y la toma de decisiones, pues suministra en forma oportuna y sistemática información relacionada con la producción (Evia, 2006, & Ramírez y Vanegas 2008; citado en (Duarte Cáceres, Uc Heredia, & Martín Méndez, 2011))[@DuarteHeredia].

Así mismo, Lee 2011 citado en Duarte Cáceres, Uc Heredia, & Martín Méndez, 2011, pág. 5 [@DuarteHeredia pp. 5] señala que la información relevante, exacta y oportuna que se obtiene como beneficio de un cambio de sistema de contabilidad de costos, no solamente es útil para fines internos de gestión, sino que también genera datos sobre la consideración de posibles riesgos e implicaciones financieras asociadas con la toma de decisiones del medio en el que se desenvuelve la empresa, es decir, se genera información para la toma de decisiones relacionadas con el interior y el exterior de la organización.

Atendiendo a Ortiguera se entiende que: "la Contabilidad de Costes es un útil determinante para lograr una mayor eficiencia y eficacia pública, en la medida en que es clave para una buena asignación de recursos, planificar, controlar, realizar un seguimiento de la ejecución planeada, medir y controlar la eficacia social de las administraciones y sus órganos operativos." (Ortiguera Bouzada, 1988, pág. 9)[@Ortiguera pp. 9] 

Es importante traer a colación las razones de la American Accounting Asociation 1971 para considerar la importancia, en general, de la contabilidad de gestión dentro de la administración pública. (i) La actividad pública afecta a un ámbito mayor que el privado; (ii) La ausencia de un ánimo de lucro imposibilita una medida de la eficiencia operativa; y, (iii) No existe un grupo económico interesado, como los accionistas, que evalúe la eficiencia en el uso de los recursos de la institución (López Esteban, 2013, pág. 9)[@LopezEsteban pp.9]

## ¿Cuáles son las dificultades de la implementación de los sistemas de costos en las universidades?

Para implementar un sistema de costeo idóneo y que responda adecuadamente a los objetivos planteados, se hace necesario eliminar las barreras que se presenten antes, durante y después de su ejecución; por lo que en este punto es importante recordar a Waldrow (2005) Citado en Duarte Cáceres, Uc Heredia, & Martín Méndez, 2011, Pág. 6 [@DuarteHeredia pp. 6], quien afirma que: "la adopción de técnicas de contabilidad de gestión avanzada es baja, al confirmar que se siguen utilizando métodos tradicionales en la mayoría de las empresas; según esta autora, lo anterior se debe a que existen barreras en la adopción, pues de otra manera la adopción de nuevas técnicas sería alta. En este sentido, varios trabajos han demostrado la importancia de analizar la influencia de los factores y barreras del cambio en los sistemas de información con la finalidad de controlar sus efectos al realizar el cambio".

En este sentido se pueden mencionar algunas barreras que impiden la adopción de nuevos sistemas de costeo: (i) Percepción de incremento de trabajo del personal de Contabilidad con la adopción de nuevos sistemas; (ii) Dificultades en el intento de cambiar hábitos operativos; (iii) Sistemas informacionales poco flexibles que no permiten re-estructurar la obtención de información conforme a las nuevas necesidades; (iv) Falta de conocimiento en el personal; (v) Ausencia análisis costo -- beneficio de su implementación, (vi) Uso de informes e indicadores triviales que fueron implementados por las primeras administraciones que nunca han sido revisados y/o actualizados.
